services:
  - docker
  
script:
  - docker build -t test-image:test . --build-arg CONF_REPO=https://github.com/VirtualFlyBrain/vfb-pipeline-config.git CONF_BRANCH=dev
  - docker run -d --name test -v data:/data -v backup:/backup -p 7474:7474 -p 7473:7473 -p 7687:7687 test-image:test
  - sleep 2m
  - curl -sSf http://localhost:7474/browser/
  - docker restart test
  - sleep 1m
  - docker logs test
  - curl -sSf http://localhost:7474/browser/ 
